### ISSUE TITLE
Class instead of Inline for colors

### ISSUE THREAD

**Issue by tpartee** [KillerCodeMonkey/ng-quill#124]
Hey @KillerCodeMonkey - thank you so much for your hard work on this project, I love being able to use Quill in my NG projects!

I've been trying to figure out how to switch to using Class-based colors instead of Inline-colors as explained in the Quill JS documentation here under the "Class vs Inline" section: https://quilljs.com/guides/how-to-customize-quill/

I don't see how to do the import and register for the ColorClass (module? attributor? I'm not sure what it is) when using ng-quill but I want to use classes for colors rather than RGB. Reason being, I am using one code set for numerous sites with different styles/themes and I need to be able to control the colors per-site so they don't clash with the backgrounds. Allowing users to use the 35-color inline RGB picker on my sites allows them to screw things up (which they will do often) so using classes allows me fine-grained control per theme.

On a side note, I would love to see more documentation with detailed examples of how to do X or Y. Most of the time I have to resort to lengthy trial and error efforts because there are few examples out there on using ng-quill. I'd be happy to contribute if there's a place for documenting such things!

Thank you.

**Comment by KillerCodeMonkey** [comment]
thanks for the question.

in general you are using and configuring quill like it is described in the documentation of quilljs.

NgQuill is only a wrapper, where you can pass your modules configuration and set some addons, like using ngModel to handle you editor values and so on.

So for you --> follow the guide here:
https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline

before you create your angular app register the necessary Modules to Quill. 
The part of creating the final editor instance is done by ng-quill

For a little playground, you can use the demo.html of this project and extend it. 
So i will not at a full featured documentation, because everything can be done like in the quilljs-documentation. The only difference is how you create the editor instance with ng-quill + the special events.

**Comment by KillerCodeMonkey** [comment]
Any questions about it? or i will close this issue

**Comment by tpartee** [comment]
No, no more questions - I got it configured just fine. Thank you for the info!
