### ISSUE TITLE
Bower package missing dist folder

### ISSUE THREAD

**Issue by varoot** [KillerCodeMonkey/ng-quill#129]
After running `bower install nq-quill --save`, the `dist` folder is not there

**Comment by KillerCodeMonkey** [comment]
then you can use the original sources or build the dist files on your own.
bower is dead and i only registered it there because somebody asks for.

you should use the npm way to install your dependencies.

i could add a .bowerrc with a postinstall script, which would use my node tasks to create the dist folder and files. But this would be useless, because then you need to have npm installed and can simply use `npm install`

**Comment by sdsanders** [comment]
If anyone is using a build tool that automatically tries to pull in the dist file, you can fix this by adding an `overrides` section to your `bower.json`:
```
  "overrides": {
    "ngQuill": {
      "main": ["src/ng-quill.js"]
    }
  }
```

**Comment by KillerCodeMonkey** [comment]
Would you add a PR with this additonal info in the readme, Please?




Am 06.11.2017 19:09 schrieb "Steve Sanders" <notifications@github.com>:

If anyone is using a build tool that automatically tries to pull in the
dist file, you can fix this by adding an overrides section to your
bower.json:

  "overrides": {
    "ngQuill": {
      "main": ["src/ng-quill.js"]
    }
  }

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ng-quill/issues/129#issuecomment-342235351>,
or mute the thread

**Comment by sdsanders** [comment]
@KillerCodeMonkey I think the better solution would be to change the bower.json to point to `/src/ng-quill.js` instead of the dist file. I'll submit a PR for that.
