### ISSUE TITLE
No option to configure custom options apart from passing the Quill import path

### ISSUE THREAD

**Issue by kdeclerck** [KillerCodeMonkey/ng-quill#138]
For example I can't do something like this in ng-quill:

```javascript
var Block = Quill.import('blots/block');
Block.tagName = 'DIV';
Quill.register(Block, true);
```

There is no way to specifiy the tagName attribute for example. Is there a workaround for this?  Would adding this functionality be an option?

**Comment by KillerCodeMonkey** [comment]
nope, because i had to do this in a more generic way - i am not a friend of this. And you would add these options globally for all quill instances on your page. 

I would not expect this, if i pass an option to a component ;).
Even i do not know which modules will be available in the future.

If there would be a unified module api like 
```
var Block = Quill.import('blots/block');
Block.options = { tagName: 'DIV' };
Quill.register(Block, true);
```
i could move it, but there is always the problem that you will change your global Quill-Object with that.

there is a `custom-options` config to add fonts and fontsizes to ng-quill (it was a PR, but i would not recommend to use it).
