### ISSUE TITLE
Incoherence with ng-model

### ISSUE THREAD

**Issue by freitasskeeled** [KillerCodeMonkey/ng-quill#147]
The issue is related with the behaviour with ng-model and clearing the content/initial state.

So, when the page renders, the ng-model is undefined. If you change the editor content and clear the text, the ng-model will have a default empty tag

`<div><br></div>`

Is there any way of avoiding this?
I would like to set the model with undefined when there is no text in the editor (in both scenarios).

Thanks

**Comment by KillerCodeMonkey** [comment]
it behaves in this way, because this is the default behavior of quilljs.
There is nothing like an "empty" editor.

So i do not know if changing the default behaviour of quilljs is a good approach. So until now, i would say, add a check on your own --> if your model conains "<div><br></div>" handle it like null or empty string

**Comment by freitasskeeled** [comment]
Hi, thanks for the answer. It's really something I was trying to avoid (manually checking if it has an empty block and clear it). 

Could we add to your wrapper like an option so we can force it to put undefined when the content is the default block? 

Thanks again.

**Comment by KillerCodeMonkey** [comment]
maybe, this is an open sourec projekt. feel free to add this possivility in a pull request ;).
I will only add features to handle the default quilljs functionality.
