### ISSUE TITLE
bower.json main is incorrect in release 3.7.0

### ISSUE THREAD

**Issue by finneym** [KillerCodeMonkey/ng-quill#154]
The main was updated from src to dist, but the bower release file structure was never updated.
Thanks,
Max

```
{
  "name": "ngQuill",
  "version": "3.7.0",
  "main": ["dist/ng-quill.js"],
  "description": "AngularJS directive for the QuillJS rich text editor",
  "authors": [
    "Bengt Weiße <bengtler@gmail.com>"
  ],
  "ignore": [
    "bower_components",
    "node_modules",
    "spec",
    "demo.html",
    "package.json",
    "Gruntfile.js"
  ],
  "dependencies": {
    "quill": "^1.1.5",
    "angular": "^1.5.8"
  },
  "keywords": [
    "quill",
    "rich text",
    "angularjs",
    "angular",
    "directive",
    "editor",
    "wysiwyg"
  ],
  "license": "MIT"
}
```
![](https://user-images.githubusercontent.com/4526874/38739885-13a9dbec-3f2e-11e8-83c6-4b1e6369f6b1.png?raw=true)

**Comment by KillerCodeMonkey** [comment]
I Do Not care about bower.  This change were made by PR. Change it back and
send me a PR and IT will be There This evening ;)

finneym <notifications@github.com> schrieb am Fr., 13. Apr. 2018, 16:23:

**Comment by KillerCodeMonkey** [comment]
I did Not dist Folder. I have a build process so You are using npm only the
dist Folder is published. A Sourcecode repository should only Contain the
plain Sourcecode.

I Do Not have that possibility with bower :)

Am 14.04.2018 9:18 nachm. schrieb "Rui Freitas" <notifications@github.com>:

Yeah I also noticed that when I update the version to the latest. May I ask
why you decided to remove the dist folder/min version?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ng-quill/issues/154#issuecomment-381353381>,
or mute the thread
