### ISSUE TITLE
ng-quill-editor Page Unresponsive

### ISSUE THREAD

**Issue by nirmalkumarg** [KillerCodeMonkey/ng-quill#156]
Hi Team,

When I use ng-quill-editor chrome will become unresponsive. Eventually a Page Unresponsive error message will appear. please guide me to fix this issue ASAP.

Test Scenarios:-
Enter any words in ng-quill-editor then move your cursor into any other part of your page, come back again and do cut,copy or paste, the browser will become unresponsive.

**Comment by KillerCodeMonkey** [comment]
I trink this is Not a Problem of the component here. Check Out my Demo HTML
and others are using this in Theorie Projekts without any Problem.

And You should Ask the question AT the quilljs repository First, because i
only Provide an angular wrapper ;)

nirmalkumarg <notifications@github.com> schrieb am Fr., 4. Mai 2018, 14:19:
