### ISSUE TITLE
onEditorCreated not updating

### ISSUE THREAD

**Issue by deshario** [KillerCodeMonkey/ng-quill#229]
I tried to set placeholder inside `on-editor-created` but its not working. How should i fix it ?

<img width="774" alt="Screen Shot 2563-03-04 at 11 33 40" src="https://user-images.githubusercontent.com/11426727/75845601-2b761980-5e0c-11ea-9537-f6d6e4acab03.png">

**Comment by KillerCodeMonkey** [comment]
that is not even a ng-quill issue... if you directly access the editor object you are using the native quill editor instance.

1. you can set the placeholder dynamcally over over ng-quill.. there is an config option:
https://github.com/KillerCodeMonkey/ng-quill#configuration
2. quill.options are used for initialisation so it is more a readonly thing to check, how the editor was initialised if you access it afterwards. If  you want to set the placeholder afterwards use  `editor.root.dataset.placeholder = 'my placeholder'`

the better approach is 1. because you do not need to listen on editor creation, just pass your placeholder to the ng-quill editor component as an option.

There is even a demo:
https://killercodemonkey.github.io/ng-quill/demo.html (search for a "toggle placeholder" buttone)
https://github.com/KillerCodeMonkey/ng-quill/blob/master/demo.html#L153
