### ISSUE TITLE
Global event handler

### ISSUE THREAD

**Issue by nCrafts** [KillerCodeMonkey/ng-quill#241]
Like how the global configuration can be done via ngQuillConfigProvider, is there a way to set global event handlers for events like on-content-changed?

**Comment by KillerCodeMonkey** [comment]
nope, and i will not add them (feel free to add it as a PR), because angularjs is in LTS mode since 2018, and it will die in a year. Instead of supporting developers by adding more features in a project using a dead technology i encourage them to switch to another one like vuejs, react or angular >1
