### ISSUE TITLE
I cant get the full toolbar

### ISSUE THREAD

**Issue by sinteco** [KillerCodeMonkey/ng-quill#82]
**I cant get the full toolbar**

i have  followed all the instructions like the demo shows but i cant get the full toolbar specifically image and vedio uploads.
![capture](https://cloud.githubusercontent.com/assets/24350427/22329403/1b5148ac-e3d2-11e6-9321-947d5252f741.PNG)

**Comment by KillerCodeMonkey** [comment]
show me some code ;)

**Comment by sinteco** [comment]
oh sorry my problem is solved i change my includes to library to cdn  and it worked but i have another issue am not able to save the data with image on it and another issue how can i able to resize an image after i have upload and place it where i wont. do you have some working example. my code is hear [http://stackoverflow.com/questions/41870789/ng-quill-wysiwyg-editor-not-showing-full-toolbar](url)

**Comment by KillerCodeMonkey** [comment]
i think this question have nothing to do with ngQuill.

If you are using the build in image functionality --> it will store the image as base64 in the text.
I am not supporting question about quilljs --> please ask your QuillJS questions there.

btw. please use a newser quill version (i think 1.2.0 is the latest with many fixes since 1.1.5).

**Comment by sinteco** [comment]
thank you for your help.
